package com.example.bankapp.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.bankapp.modle.LocalMoneyService;
import com.example.bankapp.modle.LocalMoneyVideo;

import com.example.bankapp.database.LocalMoneyServiceDao;
import com.example.bankapp.database.LocalMoneyVideoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig localMoneyServiceDaoConfig;
    private final DaoConfig localMoneyVideoDaoConfig;

    private final LocalMoneyServiceDao localMoneyServiceDao;
    private final LocalMoneyVideoDao localMoneyVideoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        localMoneyServiceDaoConfig = daoConfigMap.get(LocalMoneyServiceDao.class).clone();
        localMoneyServiceDaoConfig.initIdentityScope(type);

        localMoneyVideoDaoConfig = daoConfigMap.get(LocalMoneyVideoDao.class).clone();
        localMoneyVideoDaoConfig.initIdentityScope(type);

        localMoneyServiceDao = new LocalMoneyServiceDao(localMoneyServiceDaoConfig, this);
        localMoneyVideoDao = new LocalMoneyVideoDao(localMoneyVideoDaoConfig, this);

        registerDao(LocalMoneyService.class, localMoneyServiceDao);
        registerDao(LocalMoneyVideo.class, localMoneyVideoDao);
    }
    
    public void clear() {
        localMoneyServiceDaoConfig.clearIdentityScope();
        localMoneyVideoDaoConfig.clearIdentityScope();
    }

    public LocalMoneyServiceDao getLocalMoneyServiceDao() {
        return localMoneyServiceDao;
    }

    public LocalMoneyVideoDao getLocalMoneyVideoDao() {
        return localMoneyVideoDao;
    }

}
